In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Integrated_Traffic_Weather_Hyderabad.csv")
df.head()

,DateTime,Junction,Vehicles,ID,Date,Hour,Temperature,Precipitation,WindSpeed,Humidity
0,2015-11-01 00:00:00,1,15,20151101001,2015-11-01,0,26.091101,0.001659,3.0,60.0
1,2015-11-01 01:00:00,1,13,20151101011,2015-11-01,1,26.091101,0.001659,3.0,60.0
2,2015-11-01 02:00:00,1,10,20151101021,2015-11-01,2,26.091101,0.001659,3.0,60.0
3,2015-11-01 03:00:00,1,7,20151101031,2015-11-01,3,26.091101,0.001659,3.0,60.0
4,2015-11-01 04:00:00,1,9,20151101041,2015-11-01,4,26.091101,0.001659,3.0,60.0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48120 entries, 0 to 48119
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DateTime       48120 non-null  object
 1   Junction       48120 non-null  int64
 2   Vehicles       48120 non-null  int64
 3   ID             48120 non-null  int64
 4   Date           48120 non-null  object
 5   Hour           48120 non-null  int64
 6   Temperature    48120 non-null  float64
 7   Precipitation  48120 non-null  float64
 8   WindSpeed      48120 non-null  float64
 9   Humidity       48120 non-null  float64
dtypes: float64(4), int64(4), object(2)
memory usage: 3.7+ MB

In [3]:
df.isnull().sum()

DateTime         0
Junction         0
Vehicles         0
ID               0
Date             0
Hour             0
Temperature      0
Precipitation    0
WindSpeed        0
Humidity         0
dtype: int64

In [4]:
df = df.drop_duplicates()

In [5]:
# Removing duplicate rows to avoid biased analysis

In [6]:
# Convert DateTime to pandas datetime
df['DateTime'] = pd.to_datetime(df['DateTime'])

# Time-based features
df['DayOfWeek'] = df['DateTime'].dt.dayofweek
df['Month'] = df['DateTime'].dt.month
df['IsWeekend'] = df['DayOfWeek'].isin([5, 6]).astype(int)

df.head()

,DateTime,Junction,Vehicles,ID,Date,Hour,Temperature,Precipitation,WindSpeed,Humidity,DayOfWeek,Month,IsWeekend
0,2015-11-01 00:00:00,1,15,20151101001,2015-11-01,0,26.091101,0.001659,3.0,60.0,6,11,1
1,2015-11-01 01:00:00,1,13,20151101011,2015-11-01,1,26.091101,0.001659,3.0,60.0,6,11,1
2,2015-11-01 02:00:00,1,10,20151101021,2015-11-01,2,26.091101,0.001659,3.0,60.0,6,11,1
3,2015-11-01 03:00:00,1,7,20151101031,2015-11-01,3,26.091101,0.001659,3.0,60.0,6,11,1
4,2015-11-01 04:00:00,1,9,20151101041,2015-11-01,4,26.091101,0.001659,3.0,60.0,6,11,1

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numeric_cols = ['Vehicles', 'Temperature', 'Precipitation', 'WindSpeed', 'Humidity']
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

df.head()

,DateTime,Junction,Vehicles,ID,Date,Hour,Temperature,Precipitation,WindSpeed,Humidity,DayOfWeek,Month,IsWeekend
0,2015-11-01 00:00:00,1,-0.375489,20151101001,2015-11-01,0,0.0,-1.602909e-15,0.0,0.0,6,11,1
1,2015-11-01 01:00:00,1,-0.471875,20151101011,2015-11-01,1,0.0,-1.602909e-15,0.0,0.0,6,11,1
2,2015-11-01 02:00:00,1,-0.616454,20151101021,2015-11-01,2,0.0,-1.602909e-15,0.0,0.0,6,11,1
3,2015-11-01 03:00:00,1,-0.761034,20151101031,2015-11-01,3,0.0,-1.602909e-15,0.0,0.0,6,11,1
4,2015-11-01 04:00:00,1,-0.664648,20151101041,2015-11-01,4,0.0,-1.602909e-15,0.0,0.0,6,11,1

In [8]:
df.to_csv("Final_Preprocessed_Traffic_Data.csv", index=False)